### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by dbsupport** [lazydevelopers/dbs-reports#61]
_From @dbsupport on March 27, 2014 14:20_

2014-03-27 10:30:38,124 [http-8080-12] DEBUG org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql: 2014-03-27 10:30:38 org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql ServerSession(867905807) Connection(835485509) Thread(45)
FINE: SELECT id, active, author, content, factory, filename, MANIFEST, name, _stamp, upload_date, version, _cdate, _cgsid, _edate, _egsid, creator_id FROM reports.tre_pattern WHERE (id = ?)
    bind => [252]
2014-03-27 10:30:38,126 [http-8080-12] DEBUG org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql: 2014-03-27 10:30:38 org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql ServerSession(867905807) Connection(1888770736) Thread(45)
FINE: SELECT t0.name FROM reports.tre_pattern_access t0 WHERE (t0.pattern_id = ?)
    bind => [252]
2014-03-27 10:30:38,128 [http-8080-12] ERROR pl.com.dbs.reports.support.web.filter.ExceptionHandlerFilter: 7bf6c876-f393-4150-9ff9-841ee3a63d8e
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Attribute value must not be null
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:932)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:816)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:801)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:322)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:184)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:155)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at pl.com.dbs.reports.support.web.filter.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:30)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at com.googlecode.psiprobe.Tomcat60AgentValve.invoke(Tomcat60AgentValve.java:30)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Attribute value must not be null
    at org.springframework.util.Assert.notNull(Assert.java:112)
    at org.springframework.web.bind.support.DefaultSessionAttributeStore.storeAttribute(DefaultSessionAttributeStore.java:52)
    at org.springframework.web.method.annotation.SessionAttributesHandler.storeAttributes(SessionAttributesHandler.java:123)
    at org.springframework.web.method.annotation.ModelFactory.updateModel(ModelFactory.java:202)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.getModelAndView(RequestMappingHandlerAdapter.java:842)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:751)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:920)
    ... 50 more
2014-03-27 10:31:35,082 [http-8080-12] DEBUG org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql: 2014-03-27 10:31:35 org.eclipse.persistence.session.file:/C:/Program Files/Apache Software Foundation/Tomcat 6.0/webapps/reports/WEB-INF/lib/dbs-reports-app-1.1.0-SNAPSHOT.jar_dbsReportsPU_transactionType=RESOURCE_LOCAL.sql ServerSession(867905807) Connection(2036520918) Thread(45)
FINE: SELECT id, accepted, active, description, email, firstname, lastname, login, passwd, phone, _stamp, uuid, _cdate, _cgsid, _edate, _egsid, address_id, note_id, photo_id FROM reports.tpr_profile WHERE ((active = ?) AND (id = ?))
    bind => [true, 1]

_Copied from original issue: dbsupport/dbs-reports-issues#32_

**Comment by dbsupport** [comment]
_From @lazydevelopers on March 27, 2014 21:15_

Wygląda to na ta sytuację, o której mówiłem - sesja wygasła w wyniku długiego generowania raportu.
Jako rozwiązanie żeby naprawdę było porządnie powinien być jakiś kolejkowicz raportów. Czyli, generowanie raportu nie odbywa się w czasie rzeczywistym, a jedynie trafia do kolejki i jest przetwarzane asynchronicznie.
Można też zostać przy obecnym rozwiązaniu i podtrzymywać sesję w czasie oczekiwania na response.

**Comment by dbsupport** [comment]
Na teraz możemy zostaćprzy obecnym rozwiązaniu tylko podtrzymywać sesję ( i tak w ogóle bym zwiększył do 20-30 minut). Kolejkowanie zapiszę sobie jako kolejny future request.

**Comment by dbsupport** [comment]
_From @lazydevelopers on March 30, 2014 17:24_

I jak to obsłużyć? patch?

**Comment by dbsupport** [comment]
_From @lazydevelopers on March 30, 2014 21:9_

Path 1.1.1 już jest wrzucony na serwer.
Czas sesji ustawiłem na 20 min.
Loader co minute puszcza do serwera pinga który powinien podtrzymywać sesje.
